apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhbbbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhbbbbb
  template:
    metadata:
      labels:
        app: jhbbbbb
    spec:
      containers:
      - image: okteto.dev/jhbbbbb:latest
        name: jhbbbbb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "62956ca6-77f3-4817-8487-90b480195d46"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "62956ca6-77f3-4817-8487-90b480195d46"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
